// COPYRIGHT © 2025 ESRI
//
// TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
// Unpublished material - all rights reserved under the
// Copyright Laws of the United States.
//
// For additional information, contact:
// Environmental Systems Research Institute, Inc.
// Attn: Contracts Dept
// 380 New York Street
// Redlands, California, USA 92373
//
// email: contracts@esri.com

namespace MySecondMauiApp.Model;

public static class RockSpecies
{
    public static List<string> IgneousRocks =
       [
           "Adakite",
            "Agpaitic rock",
            "Andesite",
            "Alkali feldspar granite",
            "Ankaramite",
            "Anorthosite",
            "Aplite",
            "Basalt",
            "ʻAʻā",
            "Pāhoehoe",
            "Basaltic andesite",
            "Basaltic trachyandesite",
            "Mugearite",
            "Shoshonite",
            "Basanite",
            "Blairmorite",
            "Boninite",
            "Carbonatite",
            "Charnockite",
            "Enderbite",
            "Dacite",
            "Diabase",
            "Diorite",
            "Napoleonite",
            "Dunite",
            "Essexite",
            "Foidolite",
            "Gabbro",
            "Granite",
            "Granodiorite",
            "Granophyre",
            "Harzburgite",
            "Hornblendite",
            "Hyaloclastite",
            "Icelandite",
            "Ignimbrite",
            "Ijolite",
            "Kimberlite",
            "Komatiite",
            "Lamproite",
            "Lamprophyre",
            "Latite",
            "Leucitite",
            "Lherzolite",
            "Monzodiorite",
            "Monzogabbro",
            "Monzogranite",
            "Monzonite",
            "Nepheline-bearing diorite",
            "Nepheline syenite",
            "Nephelinite",
            "Norite",
            "Obsidian",
            "Pegmatite",
            "Peridotite",
            "Phonolite",
            "Phonotephrite",
            "Picrite",
            "Porphyry",
            "Pumice",
            "Pyroxenite",
            "Quartz diorite",
            "Quartz monzonite",
            "Quartzolite",
            "Rhyodacite",
            "Rhyolite",
            "Comendite",
            "Pantellerite",
            "Scoria",
            "Shonkinite",
            "Sovite",
            "Syenite",
            "Syenogranite",
            "Tachylyte",
            "Tephriphonolite",
            "Tephrite",
            "Tonalite",
            "Trachyandesite",
            "Benmoreite",
            "Trachybasalt",
            "Hawaiite",
            "Trachyte",
            "Troctolite",
            "Trondhjemite",
            "Tuff",
            "Vitrophyre",
            "Websterite",
            "Wehrlite"
       ];
    public static List<string> SedimentaryRocks = [
           "Argillite",
            "Arkose",
            "Banded iron formation",
            "Breccia",
            "Calcarenite",
            "Chalk",
            "Chert",
            "Claystone",
            "Coal",
            "Conglomerate",
            "Coquina",
            "Diamictite",
            "Diatomite",
            "Dolomite",
            "Evaporite",
            "Flint",
            "Geyserite",
            "Greywacke",
            "Gritstone",
            "Ironstone",
            "Itacolumite",
            "Jaspillite",
            "Laterite",
            "Lignite",
            "Limestone",
            "Marl",
            "Mudstone",
            "Oil shale",
            "Oolite",
            "Phosphorite",
            "Sandstone",
            "Shale",
            "Siltstone",
            "Sylvinite",
            "Tillite",
            "Travertine",
            "Tufa",
            "Turbidite",
            "Wackestone"
       ];
    public static List<string> MetamorphicRocks = [
           "Anthracite",
            "Amphibolite",
            "Blueschist",
            "Cataclasite",
            "Eclogite",
            "Gneiss",
            "Granulite",
            "Greenschist",
            "Hornfels",
            "Calcflinta",
            "Jadeitite",
            "Litchfieldite",
            "Marble",
            "Migmatite",
            "Mylonite",
            "Metaconglomerate",
            "Metapelite",
            "Metapsammite",
            "Phyllite",
            "Pseudotachylite",
            "Quartzite",
            "Schist",
            "Semipelite",
            "Serpentinite",
            "Skarn",
            "Slate",
            "Suevite",
            "Talc carbonate",
            "Soapstone",
            "Tectonite",
            "Whiteschist"
       ];


}

public enum RockType
{
    Igneous,
    Sedimentary,
    Metamorphic
}
