// SPDX-License-Identifier: Proprietary
// © 2025 Cameron Strachan, trading as Cameron's Rock Company. All rights reserved.
// Created by Cameron Strachan.
// For personal and educational use only.

namespace MySecondMauiApp.Model;

/// <summary>
/// Provides species list for each rock type, depending on the selected <see cref="Rock.RockType"/>
/// </summary>
/// <remarks>
/// The lists are partial, not exhaustive.
/// </remarks>
public static class RockSpecies
{
    public static IReadOnlyList<string> IgneousRocks =
       [
           "Adakite",
            "Agpaitic rock",
            "Andesite",
            "Alkali feldspar granite",
            "Ankaramite",
            "Anorthosite",
            "Aplite",
            "Basalt",
            "ʻAʻā",
            "Pāhoehoe",
            "Basaltic andesite",
            "Basaltic trachyandesite",
            "Mugearite",
            "Shoshonite",
            "Basanite",
            "Blairmorite",
            "Boninite",
            "Carbonatite",
            "Charnockite",
            "Enderbite",
            "Dacite",
            "Diabase",
            "Diorite",
            "Napoleonite",
            "Dunite",
            "Essexite",
            "Foidolite",
            "Gabbro",
            "Granite",
            "Granodiorite",
            "Granophyre",
            "Harzburgite",
            "Hornblendite",
            "Hyaloclastite",
            "Icelandite",
            "Ignimbrite",
            "Ijolite",
            "Kimberlite",
            "Komatiite",
            "Lamproite",
            "Lamprophyre",
            "Latite",
            "Leucitite",
            "Lherzolite",
            "Monzodiorite",
            "Monzogabbro",
            "Monzogranite",
            "Monzonite",
            "Nepheline-bearing diorite",
            "Nepheline syenite",
            "Nephelinite",
            "Norite",
            "Obsidian",
            "Pegmatite",
            "Peridotite",
            "Phonolite",
            "Phonotephrite",
            "Picrite",
            "Porphyry",
            "Pumice",
            "Pyroxenite",
            "Quartz diorite",
            "Quartz monzonite",
            "Quartzolite",
            "Rhyodacite",
            "Rhyolite",
            "Comendite",
            "Pantellerite",
            "Scoria",
            "Shonkinite",
            "Sovite",
            "Syenite",
            "Syenogranite",
            "Tachylyte",
            "Tephriphonolite",
            "Tephrite",
            "Tonalite",
            "Trachyandesite",
            "Benmoreite",
            "Trachybasalt",
            "Hawaiite",
            "Trachyte",
            "Troctolite",
            "Trondhjemite",
            "Tuff",
            "Vitrophyre",
            "Websterite",
            "Wehrlite"
       ];
    public static IReadOnlyList<string> SedimentaryRocks = [
           "Argillite",
            "Arkose",
            "Banded iron formation",
            "Breccia",
            "Calcarenite",
            "Chalk",
            "Chert",
            "Claystone",
            "Coal",
            "Conglomerate",
            "Coquina",
            "Diamictite",
            "Diatomite",
            "Dolomite",
            "Evaporite",
            "Flint",
            "Geyserite",
            "Greywacke",
            "Gritstone",
            "Ironstone",
            "Itacolumite",
            "Jaspillite",
            "Laterite",
            "Lignite",
            "Limestone",
            "Marl",
            "Mudstone",
            "Oil shale",
            "Oolite",
            "Phosphorite",
            "Sandstone",
            "Shale",
            "Siltstone",
            "Sylvinite",
            "Tillite",
            "Travertine",
            "Tufa",
            "Turbidite",
            "Wackestone"
       ];
    public static IReadOnlyList<string> MetamorphicRocks = [
           "Anthracite",
            "Amphibolite",
            "Blueschist",
            "Cataclasite",
            "Eclogite",
            "Gneiss",
            "Granulite",
            "Greenschist",
            "Hornfels",
            "Calcflinta",
            "Jadeitite",
            "Litchfieldite",
            "Marble",
            "Migmatite",
            "Mylonite",
            "Metaconglomerate",
            "Metapelite",
            "Metapsammite",
            "Phyllite",
            "Pseudotachylite",
            "Quartzite",
            "Schist",
            "Semipelite",
            "Serpentinite",
            "Skarn",
            "Slate",
            "Suevite",
            "Talc carbonate",
            "Soapstone",
            "Tectonite",
            "Whiteschist"
       ];
}

/// <summary>
/// Enumeration of the three main types of rocks.
/// </summary>
public enum RockTypesEnum
{
    Igneous,
    Sedimentary,
    Metamorphic
}
